// <auto-generated />
namespace CourseManager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _20191218858 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20191218858));
        
        string IMigrationMetadata.Id
        {
            get { return "201906290014541_20191218858"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
