// <auto-generated />
namespace CourseManager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _201912271449 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201912271449));
        
        string IMigrationMetadata.Id
        {
            get { return "201906290649515_201912271449"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
